### PR TITLE
parse email addresses without angle brackets

### PR DESCRIPTION
**Pull request by msimerson**
closes DoubleCheck/log-ship-elastic-postfix#7

### CODE REVIEW

**Comment by msimerson** [comment]
@etfeet, try applying the `index.js` changes in this PR against your locally installed logship instance (in `logship-....-postfix/node_modules/postfix-parser/index.js`. This should solve the from parsing problem for you.

**Comment by etfeet** [comment]
@msimerson , I tried with the new index.js. However, I'm still getting the blank from field. 

here are the pertinent sections from index.js:

line 5:
var envEmailAddr   = '<?([^>,]*)>?';

line 188:
function matchAsObject (match) {
  match.shift();
  var obj = {};
  var qid = match.shift();
  if (qid) obj.qid = qid;
  while (match.length) {
    var key = match.shift();
    var val = match.shift();
    if (key === undefined) continue;
    if (val === undefined) continue;
    obj[key] = val;
  }
  return obj;
}

maillog:
Sep 25 17:14:12 rory-dev postfix/pickup[19660]: D07B4F806FC: uid=1000 from=<rory>
Sep 25 17:14:12 rory-dev postfix/cleanup[19920]: D07B4F806FC: message-id=20150926001412.D07B4F806FC@rory-dev.localdomain
Sep 25 17:14:12 rory-dev postfix/qmgr[1626]: D07B4F806FC: from=rory@rory-dev.localdomain, size=270, nrcpt=1 (queue active)
Sep 25 17:14:12 rory-dev postfix/local[19922]: D07B4F806FC: to=root@localhost.localdomain, orig_to=root@localhost, relay=local, delay=0.13, delays=0.09/0.01/0/0.03, dsn=2.0.0, status=sent (delivered to mailbox)
Sep 25 17:14:12 rory-dev postfix/qmgr[1626]: D07B4F806FC: removed

es:

{
"_index": "postfix-orphan-2015-09-25",
"_type": "postfix-orphan",
"_id": "D07B4F806FC",
"_version": 1,
"_score": null,
"_source": {
"host": "rory-dev",
"events": [
{
"date": "2015-09-25T17:14:12-07:00",
"action": "queued"
}
,
{
"to": "root@localhost.localdomain",
"orig_to": "root@localhost",
"relay": "local",
"delay": "0.13",
"delays": "0.09/0.01/0/0.03",
"dsn": "2.0.0",
"status": "sent (delivered to mailbox)",
"date": "2015-09-25T17:14:12-07:00"
}
],
"date": "2015-09-25T17:14:12-07:00",
"isFinal": false,
"uid": "1000",
"message-id": "20150926001412.D07B4F806FC@rory-dev.localdomain",
"from": ""
},
"sort": [
1443226452000
]
}

**Comment by msimerson** [comment]
It would appear the patch is not applied to the version of postfix-parser/index.js that is being run. The line 5 change is the significant one, removing the requirement for angle brackets. Perhaps you have safe-log-reader installed elsewhere?

**Comment by etfeet** [comment]
Ok,

i just tested with a fresh install of centos 7 and the new regex does not appear to be working.

npm i log-ship-elastic-postfix
edited config file and copied to /etc/
updated line 5 on index.js -> var envEmailAddr = '<?([^>,]*)>?';
during run parser failed to match any postfix log lines (line 196-198).
edited index.js and updated match.length lines.
parserer matched the postfix logs however from field is still empty.

any ideas?

Thanks,

Rory

**Comment by msimerson** [comment]
Sorry @etfeet , I really don't know what's happening. I copy/pasted into the new test **exactly** one of the lines from your issue and then updated the code so _that exact log message_ you had issues with would parse.  It does for me, and Travis testing, but not for you. Something is amiss.

Instead of summarizing what you did that didn't work, gist the entire session log, along with `diff -c` output after patching, and then perhaps I can see what the issue is.

**Comment by jaredj** [comment]
This PR looks like progress to me anyway; why don't we merge it to master so that @etfeet can cut out one manual step from his testing process and test master directly to reduce the likelihood of error?

**Comment by msimerson** [comment]
I like to have confirmation that a PR actually solves the problem before merging, but the added test case provides enough validation that I'm very confident.

**Comment by msimerson** [comment]
version 1.0.3 is released on npm:

```
[matt@imac27] $ npm publish
+ postfix-parser@1.0.3
```

**Comment by etfeet** [comment]
ok i just tried a fresh install from npm. However, from field is still blank but I'm getting the following error when log ship is running.

[root@localhost log-ship-elastic-postfix ~] # node server.js
missing required arg
PARSE ERROR for syslog:
missing required arg
PARSE ERROR for syslog:
end of /var/log/maillog
doQueue: 15 lines
watching /var/log/maillog
        elastic doc matches: 2
        updatePfDocs: new: 1
        saveResultsToEs: ok

below is output from npm install:

[root@localhost ~]# npm i log-ship-elastic-postfix
npm http GET https://registry.npmjs.org/log-ship-elastic-postfix
npm http 304 https://registry.npmjs.org/log-ship-elastic-postfix
npm http GET https://registry.npmjs.org/moment-timezone
npm http GET https://registry.npmjs.org/safe-log-reader
npm http GET https://registry.npmjs.org/ini
npm http GET https://registry.npmjs.org/elasticsearch
npm http GET https://registry.npmjs.org/postfix-parser
npm http 304 https://registry.npmjs.org/ini
npm http 304 https://registry.npmjs.org/safe-log-reader
npm http 304 https://registry.npmjs.org/elasticsearch
npm http 304 https://registry.npmjs.org/postfix-parser
npm http 304 https://registry.npmjs.org/moment-timezone
npm http GET https://registry.npmjs.org/chalk
npm http GET https://registry.npmjs.org/forever-agent
npm http GET https://registry.npmjs.org/bluebird
npm http GET https://registry.npmjs.org/lodash-compat
npm http GET https://registry.npmjs.org/lodash
npm http GET https://registry.npmjs.org/moment
npm http 304 https://registry.npmjs.org/chalk
npm http 304 https://registry.npmjs.org/forever-agent
npm http 304 https://registry.npmjs.org/moment
npm http 304 https://registry.npmjs.org/bluebird
npm http 304 https://registry.npmjs.org/lodash
npm http 304 https://registry.npmjs.org/lodash-compat
npm http GET https://registry.npmjs.org/ansi-styles
npm http GET https://registry.npmjs.org/escape-string-regexp
npm http GET https://registry.npmjs.org/strip-ansi
npm http GET https://registry.npmjs.org/has-ansi
npm http GET https://registry.npmjs.org/supports-color
npm http 304 https://registry.npmjs.org/ansi-styles
npm http 304 https://registry.npmjs.org/strip-ansi
npm http 304 https://registry.npmjs.org/supports-color
npm http 304 https://registry.npmjs.org/escape-string-regexp
npm http 304 https://registry.npmjs.org/has-ansi
npm http GET https://registry.npmjs.org/ansi-regex
npm http 304 https://registry.npmjs.org/ansi-regex
log-ship-elastic-postfix@0.9.0 node_modules/log-ship-elastic-postfix
├── ini@1.3.4
├── safe-log-reader@0.9.9
├── postfix-parser@1.0.3
├── elasticsearch@8.2.0 (forever-agent@0.6.1, chalk@1.1.1, bluebird@2.10.1, lodash@3.10.1, lodash-compat@3.10.1)
└── moment-timezone@0.4.0 (moment@2.10.6)

maillog:
Sep 30 10:41:55 localhost postfix/pickup[2520]: 0ECF844283: uid=0 from=<root>
Sep 30 10:41:55 localhost postfix/cleanup[11971]: 0ECF844283: message-id=20150930174155.0ECF844283@localhost.localdomain
Sep 30 10:41:55 localhost postfix/qmgr[2521]: 0ECF844283: from=root@localhost.localdomain, size=821, nrcpt=1 (queue active)
Sep 30 10:41:55 localhost postfix/local[11973]: 0ECF844283: to=root@localhost.localdomain, orig_to=root@localhost, relay=local, delay=0.09, delays=0.04/0.05/0/0, dsn=2.0.0, status=sent (delivered to mailbox)
Sep 30 10:41:55 localhost postfix/qmgr[2521]: 0ECF844283: removed

es document:

{

```
"_index": "postfix-orphan-2015-09-30",
"_type": "postfix-orphan",
"_id": "0ECF844283",
"_version": 1,
"_score": 1,
"_source": {
    "host": "localhost",
    "events": [
        {
            "date": "2015-09-30T10:41:55-07:00",
            "action": "queued"
        }
        ,
        {
            "to": "root@localhost.localdomain",
            "orig_to": "root@localhost",
            "relay": "local",
            "delay": "0.09",
            "delays": "0.04/0.05/0/0",
            "dsn": "2.0.0",
            "status": "sent (delivered to mailbox)",
            "date": "2015-09-30T10:41:55-07:00"
        }
    ],
    "date": "2015-09-30T10:41:55-07:00",
    "isFinal": false,
    "uid": "0",
    "message-id": "20150930174155.0ECF844283@localhost.localdomain",
    "from": ""
}
```

}

if I try to run the test modules for the log parser I get the following errors:

[root@localhost log-ship-elastic-postfix ~] # node ~/node_modules/log-ship-elastic-postfix/node_modules/postfix-parser/test/index.js

/root/node_modules/log-ship-elastic-postfix/node_modules/postfix-parser/test/index.js:83
describe('syslog lines', function () {
^
ReferenceError: describe is not defined
    at Object.<anonymous> (/home/root/node_modules/log-ship-elastic-postfix/node_modules/postfix-parser/test/index.js:83:1)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:929:3

I get this if i try the test module for the log shipper:

[root@localhost log-ship-elastic-postfix ~] # node test/logship.js

/root/node_modules/log-ship-elastic-postfix/test/logship.js:14
describe('log-ship-elastic-postfix', function () {
^
ReferenceError: describe is not defined
    at Object.<anonymous> (/root/node_modules/log-ship-elastic-postfix/test/logship.js:14:1)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:929:3

are there any dependencies that i need to install etc for this to work? is there any kind of debug logging that I can turn on?

Thanks,

Rory

**Comment by msimerson** [comment]
```
[root@localhost log-ship-elastic-postfix ~] # node ~/node_modules/log-ship-elastic-postfix/node_modules/postfix-parser/test/index.js
```

That won't work, the tests are run via the test runner [mocha](http://mochajs.org). If mocha isn't already installed (it's a dev dependency), then it can be installed with: `npm install`, and then the tests can be run with `cd postfix-parser; mocha test/logship.js`

**Comment by etfeet** [comment]
OK,

i tried installing ubuntu server 14.04.3 and installing npm, etc. to same effect.

also when i run mocha i get the following errors:

root@ubuntu:~/node_modules/log-ship-elastic-postfix# mocha test/logship.js

  log-ship-elastic-postfix
    readLogLine
      ✓ receives a log line, parses, appends to queue
missing required arg
PARSE ERROR for syslog:
PARSE ERROR for syslog:Jul 30 00:10:11 imac27 madeup: Gobbely Gook
end of /root/node_modules/log-ship-elastic-postfix/test/mail.log
doQueue: 4 lines
watching /root/node_modules/log-ship-elastic-postfix/test/mail.log
      1) ignores other lines
        elastic doc matches: 0
        updatePfDocs: new: 2
    updatePfDocs
        updatePfDocs: new: 1
      2) applies log lines to pfDocs
{ status: '400',
  message: 'ActionRequestValidationException[Validation Failed: 1: type is missing;2: type is missing;]' }
    getIndexName
      ✓ returns a static index name
missing required arg
PARSE ERROR for syslog:
PARSE ERROR for syslog:Jul 30 00:10:11 imac27 madeup: Gobbely Gook
      ✓ date template year
end of /root/node_modules/log-ship-elastic-postfix/test/mail.log
doQueue: 6 lines
watching /root/node_modules/log-ship-elastic-postfix/test/mail.log
        elastic doc matches: 0
        updatePfDocs: new: 2
      ✓ date template month
{ status: '400',
  message: 'ActionRequestValidationException[Validation Failed: 1: type is missing;2: type is missing;3: type is missing;]' }
      ✓ date template day

  5 passing (104ms)
  2 failing

  1) log-ship-elastic-postfix readLogLine ignores other lines:
     AssertionError: { qid: '3mPVKl0Mhjz7sXv',
  'message-id': 'E1ZB06G-0006n5-Vp@anc-dev-web1.slc.example.net',
  host: 'prd-mx1',
  prog: 'postfix/cleanup',
  date: '2015-07-05T06:52:11-07:00' }
      at Context.<anonymous> (test/logship.js:39:20)

  2) log-ship-elastic-postfix updatePfDocs applies log lines to pfDocs:

```
  AssertionError: { qid: '3mfHGL1r9gzyQP',
```

  host: 'mx12',
  events:
   [ { date: '2015-07-26T04:18:34-07:00', action: 'queued' },
     { to: 'system',
       relay: '127.0.0.2[127.0.0.2]:25',
       dsn: '2.0.0',
       status: 'sent (250 Queued! (#2.0.0))',
       date: '2015-07-26T04:18:34-07:00' } ],
  date: '2015-07-26T04:18:34-07:00',
  isFinal: false,
  from: '',
  size: undefined,
  nrcpt: undefined,
  delay: '0.53',
  delays: '0.13/0/0.23/0.16' }
      + expected - actual

```
         "relay": "127.0.0.2[127.0.0.2]:25"
         "status": "sent (250 Queued! (#2.0.0))"
         "to": "system"
       }
  +    {
  +      "action": "removed"
  +      "date": "2015-07-26T04:18:34-07:00"
  +    }
     ]
  -  "from": ""
  +  "from": "system"
     "host": "mx12"
  -  "isFinal": false
  -  "nrcpt": [undefined]
  -  "size": [undefined]
  +  "isFinal": true
  +  "nrcpt": "1"
  +  "qid": "3mfHGL1r9gzyQP"
  +  "size": "813"
   }

  at test/logship.js:56:28
  at PostfixToElastic.updatePfDocs (lib/logship.js:228:5)
  at Context.<anonymous> (test/logship.js:55:21)
```

**Comment by etfeet** [comment]
mocha fails with the following errors on centos 7:

[root@localhost log-ship-elastic-postfix]# mocha test/logship.js

  log-ship-elastic-postfix
    readLogLine
      ✓ receives a log line, parses, appends to queue
      ✓ ignores other lines
    updatePfDocs
        updatePfDocs: new: 1
      1) applies log lines to pfDocs
    getIndexName
      ✓ returns a static index name
      ✓ date template year
      ✓ date template month
      ✓ date template day

  6 passing (67ms)
  1 failing

  1) log-ship-elastic-postfix updatePfDocs applies log lines to pfDocs:

```
  AssertionError: { qid: '3mfHGL1r9gzyQP',
```

  host: 'mx12',
  events:
   [ { date: '2015-07-26T04:18:34-07:00', action: 'queued' },
     { to: 'system',
       relay: '127.0.0.2[127.0.0.2]:25',
       dsn: '2.0.0',
       status: 'sent (250 Queued! (#2.0.0))',
       date: '2015-07-26T04:18:34-07:00' } ],
  date: '2015-07-26T04:18:34-07:00',
  isFinal: false,
  from: '',
  size: undefined,
  nrcpt: undefined,
  delay: '0.53',
  delays: '0.13/0/0.23/0.16' }
      + expected - actual

```
         "relay": "127.0.0.2[127.0.0.2]:25"
         "status": "sent (250 Queued! (#2.0.0))"
         "to": "system"
       }
  +    {
  +      "action": "removed"
  +      "date": "2015-07-26T04:18:34-07:00"
  +    }
     ]
  -  "from": ""
  +  "from": "system"
     "host": "mx12"
  -  "isFinal": false
  -  "nrcpt": [undefined]
  +  "isFinal": true
  +  "nrcpt": "1"
     "qid": "3mfHGL1r9gzyQP"
  -  "size": [undefined]
  +  "size": "813"
   }

  at test/logship.js:56:28
  at PostfixToElastic.updatePfDocs (lib/logship.js:228:5)
  at Context.<anonymous> (test/logship.js:55:21)
```

**Comment by etfeet** [comment]
Ok this doesn't look like a problem with the actual parser. When i run mocha against the parser it checks out fine.

However,

if run mocha against log-ship-elastic-postfix it fails with the following:

  1) log-ship-elastic-postfix updatePfDocs applies log lines to pfDocs:

```
  AssertionError: { qid: '3mfHGL1r9gzyQP',
```

  host: 'mx12',
  events:
   [ { date: '2015-07-26T04:18:34-07:00', action: 'queued' },
     { to: 'system',
       relay: '127.0.0.2[127.0.0.2]:25',
       dsn: '2.0.0',
       status: 'sent (250 Queued! (#2.0.0))',
       date: '2015-07-26T04:18:34-07:00' } ],
  date: '2015-07-26T04:18:34-07:00',
  isFinal: false,
  from: '',
  size: undefined,
  nrcpt: undefined,
  delay: '0.53',
  delays: '0.13/0/0.23/0.16' }
      + expected - actual

```
         "relay": "127.0.0.2[127.0.0.2]:25"
         "status": "sent (250 Queued! (#2.0.0))"
         "to": "system"
       }
  +    {
  +      "action": "removed"
  +      "date": "2015-07-26T04:18:34-07:00"
  +    }
     ]
  -  "from": ""
  +  "from": "system"
     "host": "mx12"
  -  "isFinal": false
  -  "nrcpt": [undefined]
  +  "isFinal": true
  +  "nrcpt": "1"
     "qid": "3mfHGL1r9gzyQP"
  -  "size": [undefined]
  +  "size": "813"
   }

  at test/logship.js:56:28
  at PostfixToElastic.updatePfDocs (lib/logship.js:228:5)
  at Context.<anonymous> (test/logship.js:55:21)
```

the email regex in the parser index.js does not seem to matter. Changing the regex value to pre-commit and post-commit values does not affect the results of the mocha test.

ie 
var envEmailAddr   = '<?([^>,]_)>?';
var envEmailAddr   = '<([^>]_)>';

Any ideas?

**Comment by msimerson** [comment]
I've just installed the latest version via npm in a new Ubuntu 14 (it's what I had quickly available) and the entire test suite passes normally (as I expected). I do most of the development on Mac OS X and it works just fine there as well. Now that all the PRs are merged, version numbers are incremented, and updates are all published on npm, try reinstalling:

```
rm -rf log-ship-elastic-postfix
npm install log-ship-elastic-postfix
cd log-ship-elastic-postfix
npm install
mocha
```

And see if you don't get happy results that look like mine:

```
  log-ship-elastic-postfix
    readLogLine
      ✓ receives a log line, parses, appends to queue
      ✓ ignores other lines
    updatePfDocs
      ✓ applies log lines to pfDocs
    getIndexName
      ✓ returns a static index name
      ✓ date template year
      ✓ date template month
      ✓ date template day

  postfix-doc
    ✓ configured parser loads
    addEvent
      ✓ appends an event to a doc
      ✓ does not append duplicate event
      ✓ does not append subsequent queue events
    update
      ✓ updates a postfix doc with a qmgr line 
      ✓ updates the postfix doc with a pickup line
      ✓ updates the postfix doc with a bounce line
      ✓ updates the postfix doc with an error line

  log-ship-elastic-postfix
    reader
      - needs elasticsearch available

  log-ship-elastic-postfix
    spool
      ✓ spool dir is defined
      ✓ spool dir is writable
      ✓ errs if spool dir is not writable
    fs utilities
      ✓ isDirectory reports true for dir
      ✓ isDirectory reports false for file
      ✓ isWritable reports true for writable dir
      ✓ isWritable reports false for non-writable dir
      ✓ isWritablePreV12 reports true for writable dir
      ✓ isWritablePreV12 reports false for non-writable dir


  33 passing (70ms)
  2 pending
```

**Pull request merged**
